### ISSUE TITLE
The right click context menu can't be downloaded

### ISSUE THREAD

**Issue by m5687946568** [zluo01/aria2-extension#165]
![圖片](https://user-images.githubusercontent.com/39809467/131256058-49b1d4ce-f28b-4cb8-825f-f9189d173e76.png)

**Comment by zluo01** [comment]
网站和下载链接都是啥， 显示的错误是没有权限。

**Comment by m5687946568** [comment]
幾乎每個都不行
例如:https://www.amd.com/zh-hant/support/graphics/radeon-rx-vega-series/radeon-rx-vega-series/radeon-rx-vega-56

**Comment by zluo01** [comment]
> 幾乎每個都不行
> 例如:https://www.amd.com/zh-hant/support/graphics/radeon-rx-vega-series/radeon-rx-vega-series/radeon-rx-vega-56

你是右键点击哪个地方下载出现这个error？ 我这里可以正常下载。

**Comment by m5687946568** [comment]
補充一下 發生問題德情況是 第一次安裝 且沒用任何腳本

**Comment by m5687946568** [comment]
![圖片](https://user-images.githubusercontent.com/39809467/131263145-7e0338c2-d91b-4dd3-8c4b-6957c10c652a.png)

**Comment by zluo01** [comment]
> ![圖片](https://user-images.githubusercontent.com/39809467/131263145-7e0338c2-d91b-4dd3-8c4b-6957c10c652a.png)

我这里是可以右键加入下载的，但是没有下载速度是因为没有正确的referer. 只有点击了下载才能有正确的referer， 就能正常下载了。

<img width="346" alt="Screen Shot 2021-08-29 at 12 37 24" src="https://user-images.githubusercontent.com/12102011/131263262-df9ec2ad-984d-4f13-893a-79654e46b95e.png">
<img width="1213" alt="Screen Shot 2021-08-29 at 12 37 37" src="https://user-images.githubusercontent.com/12102011/131263264-6bdee34b-12eb-4f5c-a537-ef630c0faa09.png">
<img width="977" alt="Screen Shot 2021-08-29 at 12 38 03" src="https://user-images.githubusercontent.com/12102011/131263265-9c33c735-e3b0-417e-92c7-ec177ce1a010.png">
<img width="1399" alt="Screen Shot 2021-08-29 at 12 38 13" src="https://user-images.githubusercontent.com/12102011/131263267-e878c7d6-1691-48b1-95cc-f65e4cd904e0.png">

**Comment by m5687946568** [comment]
我這邊有測試一下
當全新安裝 設定如下
![圖片](https://user-images.githubusercontent.com/39809467/131263364-26675489-f9e7-44e8-a669-e67d09bc37ed.png)
這樣就會出錯
然而 使用範例的腳本後 才可以正常的右鍵下載
但是 刪除腳本後 腳本的功用依然有效

我原先是只想要右鍵下載的方式 不希望自動使用此附加元件下載

**Comment by zluo01** [comment]
> 我這邊有測試一下
> 當全新安裝 設定如下
> ![圖片](https://user-images.githubusercontent.com/39809467/131263364-26675489-f9e7-44e8-a669-e67d09bc37ed.png)
> 這樣就會出錯
> 然而 使用範例的腳本後 才可以正常的右鍵下載
> 但是 刪除腳本後 腳本的功用依然有效
> 
> 我原先是只想要右鍵下載的方式 不希望自動使用此附加元件下載

OK， 我看一下啥问题。

**Comment by zluo01** [comment]
@m5687946568 你的浏览器是啥， Firefox 还是Chrome ，能不能分享一下你的脚本。 我这边无法复现你说的问题。

**Comment by m5687946568** [comment]
Firefox 沒用腳本

**Comment by zluo01** [comment]
> Firefox 沒用腳本

```
然而 使用範例的腳本後 才可以正常的右鍵下載
但是 刪除腳本後 腳本的功用依然有效
```
这是什么情况？

**Comment by m5687946568** [comment]
我後來有在試一次
腳本刪除後 腳本的功能確實沒了
所以 目前的問題是
要使用腳本之後 才可以使用右鍵下載功能

**Comment by m5687946568** [comment]
我找到原因了
![圖片](https://user-images.githubusercontent.com/39809467/131267504-44905c7f-1206-40d0-8eb3-44e9607e940a.png)
附加元件要在不允許隱私模式執行 功能才會正常

**Comment by zluo01** [comment]
> 我找到原因了
> ![圖片](https://user-images.githubusercontent.com/39809467/131267504-44905c7f-1206-40d0-8eb3-44e9607e940a.png)
> 附加元件要在不允許隱私模式執行 功能才會正常

不允许还是允许？ 我这里一直都是`Run in Private Windows`, 没有遇到你的问题。

至于需要脚本才可以用右键下载应该没有这个问题才对
https://github.com/zluo01/aria2-extension/blob/main/src/utils/index.ts#L138
假如没有任何脚本，不会有任何操作，应该就直接传给aria2了。
https://github.com/zluo01/aria2-extension/blob/main/src/background/index.ts#L36。

还有也有可能你要下载的资源本身就不支持直接用URL下载，需要其他的信息，i.e. cookie headers

**Comment by m5687946568** [comment]
Firefox 91.0.2
會發生問題的步驟
先把此附加元件移除重新安裝
然後安裝好時 會跳出如下的視窗 把他"打勾"
![圖片](https://user-images.githubusercontent.com/39809467/131331596-714e5b66-587e-45bb-ba64-f812ad1a6fab.png)
接著設定好RPC 這時用右鍵下載任何連結 就會發生沒有權限

然後將附加元件中的"於隱私視窗中執行" 選擇"不允許"
便可以正常運作 之後再調回"允許" 也可以正常運作
