### ISSUE TITLE
下载逻辑问题

### ISSUE THREAD

**Issue by wnbh** [zluo01/aria2-extension#305]
我希望只有当我选择使用浏览器下载时，本地才开始下载。

**Comment by zluo01** [comment]
I am not sure what u mean. Please provide actual examples and more detail explanations.

**Comment by wnbh** [comment]
> 

有些网站捕捉到下载链接，弹出推送弹窗，在我决定是否推送之前，本地会直接开始下载，并且有的网站捕捉不到下载链接。

**Comment by zluo01** [comment]
Like I said, please provide actual example so I can reproduce the issue as it should never be the case as shown in [here](https://github.com/zluo01/aria2-extension/blob/9d91b0b931b6111e95ede16e13c5f201c293d44b/src/components/panel/index.tsx#L115). No download will get trigger until u press the button. Also, please provide your browser as well as any other download tool you are using.
