### ISSUE TITLE
Firefox 下排版错位，button只显示一点点

### ISSUE THREAD

**Issue by Remonli** [zluo01/aria2-extension#399]
如图，环境: firefox 102.1 esr , addon 网站最新版扩展。

<img width="484" alt="1659196333180" src="https://user-images.githubusercontent.com/9067053/181924957-16bb24b8-14cc-455d-bfa9-5ef0abe5c593.png">

**Comment by zluo01** [comment]
系统是啥？有没有开scaling ？ 大概率和浏览器或者系统scaling 有关系。

**Comment by Remonli** [comment]
win10 21h2 , 150%缩放。但我试了一下，改成100%也是一样的问题，应该是Firefox和chrome系的区别吧
