### ISSUE TITLE
[Feature request] Add a setting to toggle dark mode

### ISSUE THREAD

**Issue by mac1202** [zluo01/aria2-extension#431]
Hi first thank for this nice extension. Could you add a dark mode option please.

**Comment by zluo01** [comment]
It already has dark mode.

**Comment by mac1202** [comment]
Doesn't work for me. Is there a way to force the dark mode ? 
[screenshot](https://imgur.com/a/r1zcGNt)

**Comment by zluo01** [comment]
Currently no way to change it through settings.Will add it later.

**Comment by mac1202** [comment]
Ok. Thank you.

**Comment by zluo01** [comment]
Resolved as feature implemented. ddaeff9299cbe410a8858adcba342b8da505ffc6
