### ISSUE TITLE
Can only download with right click content menu

### ISSUE THREAD

**Issue by agn-gpl** [zluo01/aria2-extension#508]
After install this add-on on firefox, I found that I can only add downloads to aria2 with right click content menu. If I just left click on links which firefox's built-in download manager can normally download, nothing will happen (except opening a blank tab on some links), neither firefox nor aria2 starting download anything.

I always use private browsing mode on firefox. I hope it would not cause a problem. I used the default setting of this add-on, only changing the theme.

**Comment by zluo01** [comment]
I use private mode on my own and never face the problem. Make sure your browser setting allows pop up for new windows as the extension will create new download panel when it receives new jobs. Creating blank tab means it is working properly at gathering download information. Please provide any download link for reproduction if it is still a problem.

**Comment by agn-gpl** [comment]
@zluo01 I am sure that my browser setting allows pop up windows as other add-ons can normally open a pop up window. But after I use a new profile of firefox made by ffprofile and update the add-ons, this add-on works without any problem now. I think some of my old configs which block some 3rd party connections caused the issue (whereas some add-ons normally managed the downloads with aria2 without any problem).
