### ISSUE TITLE
Feature Request: toggle aria

### ISSUE THREAD

**Issue by yuchen-lea** [zluo01/aria2-extension#650]
I hope to be able to switch quickly between using Aria for downloads or the browser's built-in download feature.

It seems that once the extension is enabled, it will always replace browser default download manager with Aria2, unless the extension is disabled.

**Comment by zluo01** [comment]
Save button on download panel will use browser default downloaded.

**Comment by yuchen-lea** [comment]
Oh, I didn‘t notice that! Download and Save make me a little confusing... Thanks for your explanation！
